# Generated by Django 5.2 on 2025-04-19 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2025, 4, 19, 4, 32, 26, 5950, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_start',
            field=models.TimeField(default=datetime.datetime(2025, 4, 19, 4, 32, 26, 5928, tzinfo=datetime.timezone.utc)),
        ),
    ]
