# Generated by Django 5.1.6 on 2025-04-19 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_timeslot_time_end_alter_timeslot_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2025, 4, 19, 4, 37, 54, 243270, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_start',
            field=models.TimeField(default=datetime.datetime(2025, 4, 19, 4, 37, 54, 243134, tzinfo=datetime.timezone.utc)),
        ),
    ]
