# Generated by Django 4.2.11 on 2025-04-10 04:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_class_student_teacher_delete_classtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name=datetime.datetime(2025, 4, 10, 4, 18, 12, 939017, tzinfo=datetime.timezone.utc))),
                ('time_end', models.TimeField(verbose_name=datetime.datetime(2025, 4, 10, 4, 18, 12, 939029, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='class_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='class_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.classtime'),
        ),
    ]
