# Generated by Django 4.2.11 on 2025-04-10 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_classtime_class_class_date_alter_class_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='time_end',
            field=models.TimeField(verbose_name=datetime.datetime(2025, 4, 10, 5, 5, 55, 989258, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='time_start',
            field=models.TimeField(verbose_name=datetime.datetime(2025, 4, 10, 5, 5, 55, 989247, tzinfo=datetime.timezone.utc)),
        ),
    ]
