# Generated by Django 4.2.11 on 2025-04-10 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_classtime_time_end_alter_classtime_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='time_end',
            field=models.TimeField(verbose_name=datetime.datetime(2025, 4, 10, 5, 17, 22, 111198, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='time_start',
            field=models.TimeField(verbose_name=datetime.datetime(2025, 4, 10, 5, 17, 22, 111186, tzinfo=datetime.timezone.utc)),
        ),
    ]
