# Generated by Django 4.2.11 on 2025-04-10 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_alter_classtime_time_end_alter_classtime_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2025, 4, 10, 8, 30, 43, 586027, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='time_start',
            field=models.TimeField(default=datetime.datetime(2025, 4, 10, 8, 30, 43, 586013, tzinfo=datetime.timezone.utc)),
        ),
    ]
